### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Samathingamajig** [t3dotgg/paycheck-extension#16]
Some people want this extension to work in Firefox and to be published on the Add-ons marketplace.

This issue will track progress of this feature, including if it's wontfix.

I don't have any experience with making Firefox Add-ons (probably should work as-is since this is just a content script, might need another manifest), so if someone else wants to make the necessary changes that would be epic.

<img width="597" alt="image" src="https://github.com/t3dotgg/paycheck-extension/assets/29130894/00891089-ce09-4ccb-b960-4a254f8f2383">

https://twitter.com/TimRamboReal/status/1689408815186284545?s=20

**Comment by Krymancer** [comment]
No need to have an additional manifest, Firefox supports the v3 manifest right now!

But for the time being I was not able to make the extension function in Firefox, takes forever and freezes the page, maybe if I can find what is happening I will make a PR

**Comment by Krymancer** [comment]
![image](https://github.com/t3dotgg/paycheck-extension/assets/17505605/9862ca7c-8f2b-494f-a8db-48fac718b726)

Just to clarify, it does in fact work but Firefox does not seem to like the Dom manipulation the `doWork` function

**Comment by CallMeSlinky** [comment]
> ![image](https://user-images.githubusercontent.com/17505605/259586439-9862ca7c-8f2b-494f-a8db-48fac718b726.png)
> 
> Just to clarify, it does in fact work but Firefox does not seem to like the Dom manipulation the `doWork` function

I believe I got it working, mostly assisted by ChatGPT  😆 https://github.com/CallMeSlinky/paycheck-extension-firefox

**Comment by Samathingamajig** [comment]
@CallMeSlinky please don't submit to the Firefox store like you said you have done in your README, it should be reserved for theo to do

**Comment by CallMeSlinky** [comment]
> @CallMeSlinky please don't submit to the Firefox store like you said you have done in your README, it should be reserved for theo to do

My apologies, I have removed it from being submitted now.
