### ISSUE TITLE
when viewing your own tweet from your notifs, does not display in this view only

### ISSUE THREAD

**Issue by irvineAlgotrading** [t3dotgg/paycheck-extension#4]
![image](https://github.com/t3dotgg/paycheck-extension/assets/47344131/b5baab56-b6dd-4df9-96c8-78a6a0ccfa47)

really awesome extension, only a minor thing and you can still navigate to the prior tweet to see your reply with the estimate, but would make this thing air-tight

**Comment by ErwinAI** [comment]
Good catch @irvineAlgotrading 

Just submitted a PR that fixes this:

<img width="274" alt="image" src="https://github.com/t3dotgg/paycheck-extension/assets/2168688/f334e937-1865-4039-98e8-0ac272594275">
