### ISSUE TITLE
How to create icon?

### ISSUE THREAD

**Issue by ryota-murakami** [t3dotgg/paycheck-extension#7]
I'm just creating chrome extension related react community and not completed Icon design.  
I want to know which did you use traditional design software(like Photoshop) or LLM solution.(like Stable Stable Diffusion)

**Comment by realityzero** [comment]
You can simply use any icons from Flaticon or icons8. As for paycheck-extention, it's simple dollar sign that can be done with paint as well. For future iterations you can either design it with illustrator or use midjourney or sdxl.

**Comment by ryota-murakami** [comment]
@ryota-murakami Thank you so much!
